name: Sync Github To Image

on:
  push:
    branches: [main]
  schedule:
    # 定时任务，每天 UTC 时间 0 点运行
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync-gitee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 为了 git pull --unshallow，我们需要获取所有的提交历史

      - name: Set up Git user
        run: |
          git config --global user.email "wangfj11@foxmail.com"
          git config --global user.name "AlianBlank"

      - name: Set SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITEE_ID_RSA }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s) && ssh-add ~/.ssh/id_rsa
          # 信任域名
          ssh-keyscan -H gitee.com >> ~/.ssh/known_hosts
      # 查看当前分支
      - name: Check current branch
        run: echo 当前分支：${{ github.ref_name }} ${{ github.Repository }}
      # 查看远端 地址
      - name: echo git url
        run: echo git@gitee.com:${{ github.Repository }}.git

      # 添加远端
      - name: add remote url
        run: git remote add gitee "git@gitee.com:${{ github.Repository }}.git"

      # 获取
      - name: fetch
        run: git fetch --prune gitee --tags --verbose

      # 拉取
      - name: pull
        run: | 
          if [ "${{ github.ref_name }}" ]; then
          git checkout ${{ github.ref_name }}
          git pull --progress -v --no-rebase gitee ${{ github.ref_name }} --tags --verbose || echo 远端不存在${{ github.ref_name }}分支;
          fi

      # 推送
      - name: push
        run: | 
          if [ "${{ github.ref_name }}" ]; then
          git push -u --force gitee ${{ github.ref_name }} --tags --verbose
          fi